netflix/urls.py
from django.urls import path
from .import views

app_name="netflix"

urlpatterns = [
    path("", views.index, name="index"),
    # views.index is a reference to views.py
    path("<int:netflix_id>", views.detail, name="detail")
]

netflixapp/netflixapp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

netflixapp/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import NetflixResource
from .import views

netflix_resource = NetflixResource()


urlpatterns = [
    path("", views.home),
    path('admin/', admin.site.urls),
    path("netflix/", include("netflix.urls")),
    path(("api/"), include(netflix_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from netflix.models import Netflix

# Create your models here.


class NetflixResource(ModelResource):
    class Meta:
        queryset = Netflix.objects.all()
        resource_name = "netflix"

netflix/models.py
from django.db import models
#from django.utils import timezone

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Netflix(models.Model):
    link = models.CharField(max_length=500)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    sub_genre = models.CharField(max_length=500)
    #date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

netflix/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Netflix

# Create your views here.


def index(request):
    netflix_genres = Netflix.objects.all()
    #output = ", ".join([n.sub_genre for n in netflix])
    # return HttpResponse(output)
    return render(request, "netflix/index.html", {"netflix_genres": netflix_genres})


def detail(request, netflix_id):
        netflix_genres = get_object_or_404(Netflix, pk=netflix_id)
        return render(request, "netflix/detail.html", { "netflix_genres": netflix_genres})
    

netflixapp/views.py
from django.shortcuts import render

def home(request):
    return render (request, "home.html")

netflix/templates/netflix/detail.html
{% extends "base.html" %}

{% block content %}
<dl>
    <dt>Genre</dt>
    <dd>{{ netflix_genres.genre }}</dd>
    <dt>Sub Genre</dt>
    <dd>{{netflix_genres.sub_genre }}</dd>
    <dt>Link</dt>
    <dd>{{ netflix_genres.link }}</dd>
</dl>
{% endblock %}

netflix/templates/netflix/index.html
{% extends "base.html" %}

{% block content %}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Genre</th>
            <th>Sub Genre</th>
            <th>Link</th>
        </tr>
    </thead>
    <tbody>
        {% for netflix_genre in netflix_genres %}
        <tr>
            <td>{{ netflix_genre.genre }}</td>
            <td>{{ netflix_genre.sub_genre }}</td>
            <td>
                <a href="{{netflix_genre.link}}">{{ netflix_genre.link }}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Genres List</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        
        {% comment %} This block comment contains the HTML table structure that will be displayed 
        in the index.html file. The index file extends the base file, allowing 
        this content to be imported and displayed here.{% endcomment %}
        <main class="container">
            <h1 align="center">Netflix Genres List</h1>
            {% block content %}{% endblock %}
        </main>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <div style="text-align: center;">
        <a href="{% url 'netflix:index' %}">Welcome, Click to access the list of Netflix genres and their links
        </a>
    </div>
{% endblock %}